server:
  port: 8080
  host: "0.0.0.0"
  environment: "development"
  enable_https: false
  cert_file: ""
  key_file: ""
  read_timeout: 10
  write_timeout: 10

database:
  mvdsb:
    host: "localhost"
    port: 3306
    username: "portal64api"
    password: "password"
    database: "mvdsb"
    charset: "utf8mb4"
  
  portal64_bdw:
    host: "localhost"
    port: 3306
    username: "portal64api"
    password: "password"
    database: "portal64_bdw"
    charset: "utf8mb4"
  
  portal64_svw:
    host: "localhost"
    port: 3306
    username: "portal64api"
    password: "password"
    database: "portal64_svw"
    charset: "utf8mb4"
